version: "3.8"
services:
  frontend-web:
    container_name: frontend
    build: ./frontend
    image: frontend-web
    depends_on:
      - backend-api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  backend-api:
    container_name: backend
    build: ./backend
    image: backend-api
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks:
     - network-backend

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    # ports:
    #   - 27017:27017
    networks:
     - network-backend

networks:
  network-backend:

volumes:
  mongodb_data:
